stages:
  extract:
    foreach: ${extract.name}
    do:
      cmd: >-
        python scripts/stages/extract.py
        --name=${item}
        --output-dir=${extract.output_dir}
      params:
        - extract
      deps:
        - scripts/stages/extract.py
        - src/pbs/etl/extraction.py
      outs:
        - ${extract.output_dir}/${item}.parquet
  prepare:
    cmd: >-
      python scripts/stages/prepare.py
      --input-dir=${extract.output_dir}
      --output-path=${prepare.output_path}
    params:
      - extract
      - prepare
    deps:
      - ${extract.output_dir}
      - scripts/stages/prepare.py
      - src/pbs/etl/preparation.py
    outs:
      - ${prepare.output_path}
  split:
    cmd: >-
      python scripts/stages/split.py
      --input-path=${prepare.output_path}
      --output-path=${split.output_path}
    params:
      - prepare
      - split
    deps:
      - ${prepare.output_path}
      - scripts/stages/split.py
      - src/pbs/etl/split.py
    outs:
      - ${split.output_path}
