extract:
  output_dir: data/input
  name:
    - credit
    - hpi
    - cpi
    - ishort
    - ilong
    - crises
prepare:
  output_path: data/prepared/data.parquet
split:
  output_path: data/split/data.parquet
